[mysqldb]
host = "127.0.0.1"
user = "root"
port = 3306
database = "starwarsDB"
password = "Pranit@12"

[swapi]
home_url = "https://swapi.dev"
vehicle = "/api/vehicles"
starship = "/api/starships"
film = "/api/films"



# this file is created for configuration i.e. whenever we need to access homeurl etc we can access it through this file
# Also in future if swapi url is changed to anyother exension,then we dont need to change it in every code, simply
# we will chahnge here as we r using this file for configuration or reference.